name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: "- $TITLE (@$AUTHOR)"
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
categories:
  - title: "Features"
    labels:
      - feature
      - enhancement
  - title: "Bug Fixes"
    labels:
      - bug
      - fix
  - title: "Maintenance"
    labels:
      - chore
      - refactor
      - docs
      - ci
  - title: "Dependencies"
    labels:
      - dependencies
template: |
  ## Changes
  $CHANGES
